"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# import dj_database_url # Uncomment if using PostgreSQL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Gunakan environment variable yang diatur di Render
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-g$n!0b$x@+8y77i=)l8@)_1_h+1&26q6&!_z(+o2h*^z1h5@c=",
)  # Default untuk dev lokal

# SECURITY WARNING: don't run with debug turned on in production!
# Ambil dari environment variable, default ke False
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# Ambil allowed hosts dari environment variable, pisahkan dengan koma
ALLOWED_HOSTS_STRING = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost")
ALLOWED_HOSTS = ALLOWED_HOSTS_STRING.split(",") if ALLOWED_HOSTS_STRING else []

# Tambahkan URL layanan Render jika ada (lebih baik tentukan secara eksplisit di env var)
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",  # Tambahkan whitenoise
    "django.contrib.staticfiles",
    "corsheaders",  # Tambahkan corsheaders
    "clustering",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Tambahkan CORS middleware (biasanya di atas)
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Tambahkan whitenoise middleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Konfigurasi SQLite (cocok untuk tier gratis Render, tapi punya keterbatasan)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Contoh Konfigurasi PostgreSQL di Render (jika menggunakan)
# Pastikan Anda menginstal dj_database_url dan psycopg2-binary
# DATABASES = {
#     'default': dj_database_url.config(
#         default=f'sqlite:///{BASE_DIR / "db.sqlite3"}', # Fallback ke SQLite jika DATABASE_URL tidak ada
#         conn_max_age=600 # Waktu koneksi persisten (detik)
#     )
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
# Direktori tempat collectstatic akan mengumpulkan file statis untuk produksi
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Penyimpanan file statis Whitenoise (handle kompresi dan caching)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Pengaturan CORS (Cross-Origin Resource Sharing)
# Ambil dari environment variable, pisahkan dengan koma
# Pastikan URL frontend Anda ada di sini (gunakan HTTPS)
CORS_ALLOWED_ORIGINS = os.environ.get(
    "DJANGO_CORS_ALLOWED_ORIGINS", "http://localhost:5173,http://127.0.0.1:5173"
).split(",")

# Atau izinkan semua origin (kurang aman untuk produksi)
# CORS_ALLOW_ALL_ORIGINS = True

# Pengaturan Keamanan untuk Produksi (jika disajikan via HTTPS, seperti di Render)
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True  # Redirect HTTP ke HTTPS
SECURE_HSTS_SECONDS = 31536000  # 1 tahun (opsional, meningkatkan keamanan)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Opsional
SECURE_HSTS_PRELOAD = True  # Opsional
# Penting untuk Render agar Django tahu koneksi aman meski di belakang proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Batas Ukuran Upload File (misalnya 10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB in bytes

# Logging (opsional, sesuaikan sesuai kebutuhan)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",  # Atur ke INFO atau WARNING untuk produksi
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv(
                "DJANGO_LOG_LEVEL", "INFO"
            ),  # Sesuaikan level log Django
            "propagate": False,
        },
    },
}
